In [7]:
import pandas as pd
#to print/read the whole data;
df = pd.read_csv('pokemon_data.csv')
#prints the whole data from 0 till the end of file
print(df[0:])
#to print the column in the data
print(df.columns)
#to print top 5 rows
print(df.head())
#to print first row only
print(df.head(1))
#to print single/specific coloumn
print('\nPrinting single colmn')
print(df['Name'])
print('\nprinting multiple desired colmns')
print(df[['Name','Type 1','Attack']])
print('\nfirst row')
print(df.iloc[1])

print('\nRead specific row specific colmn')
print(df.iloc[2,1])
print('\nconditioning')
df.loc[df['Name']=="Bulbasaur"]
#print(df)
#df.sort_values(['Type 1','HP'], ascending=True)
#df['Total'] = df['HP'] + df['Attack'] + df['Defense']
#df.head(5)

#df.to_csv('modified.csv')
#filtering the data
df.loc[(df['Type 1']=='Grass' )&(df['Type 2']=='Poison')]

       #                   Name   Type 1  Type 2  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison  45      49       49
1      2                Ivysaur    Grass  Poison  60      62       63
2      3               Venusaur    Grass  Poison  80      82       83
3      3  VenusaurMega Venusaur    Grass  Poison  80     100      123
4      4             Charmander     Fire     NaN  39      52       43
..   ...                    ...      ...     ...  ..     ...      ...
795  719                Diancie     Rock   Fairy  50     100      150
796  719    DiancieMega Diancie     Rock   Fairy  50     160      110
797  720    HoopaHoopa Confined  Psychic   Ghost  80     110       60
798  720     HoopaHoopa Unbound  Psychic    Dark  80     160       60
799  721              Volcanion     Fire   Water  80     110      120

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
0         65       65     45           1      False
1         80       80     60           1      False
2        100      100     80           1      False
3        122      120     80           1      False
4         60       50     65           1      False
..       ...      ...    ...         ...        ...
795      100      150     50           6       True
796      160      110    110           6       True
797      150      130     70           6       True
798      170      130     80           6       True
799      130       90     70           6       True

[800 rows x 12 columns]
Index(['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')
   #                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
0  1              Bulbasaur  Grass  Poison  45      49       49       65
1  2                Ivysaur  Grass  Poison  60      62       63       80
2  3               Venusaur  Grass  Poison  80      82       83      100
3  3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122
4  4             Charmander   Fire     NaN  39      52       43       60

   Sp. Def  Speed  Generation  Legendary
0       65     45           1      False
1       80     60           1      False
2      100     80           1      False
3      120     80           1      False
4       50     65           1      False
   #       Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  \
0  1  Bulbasaur  Grass  Poison  45      49       49       65       65     45

   Generation  Legendary
0           1      False

Printing single colmn
0                  Bulbasaur
1                    Ivysaur
2                   Venusaur
3      VenusaurMega Venusaur
4                 Charmander
               ...
795                  Diancie
796      DiancieMega Diancie
797      HoopaHoopa Confined
798       HoopaHoopa Unbound
799                Volcanion
Name: Name, Length: 800, dtype: object

printing multiple desired colmns
                      Name   Type 1  Attack
0                Bulbasaur    Grass      49
1                  Ivysaur    Grass      62
2                 Venusaur    Grass      82
3    VenusaurMega Venusaur    Grass     100
4               Charmander     Fire      52
..                     ...      ...     ...
795                Diancie     Rock     100
796    DiancieMega Diancie     Rock     160
797    HoopaHoopa Confined  Psychic     110
798     HoopaHoopa Unbound  Psychic     160
799              Volcanion     Fire     110

[800 rows x 3 columns]

first row
#                   2
Name          Ivysaur
Type 1          Grass
Type 2         Poison
HP                 60
Attack             62
Defense            63
Sp. Atk            80
Sp. Def            80
Speed              60
Generation          1
Legendary       False
Name: 1, dtype: object

Read specific row specific colmn
Venusaur

conditioning

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
48,43,Oddish,Grass,Poison,45,50,55,75,65,30,1,False
49,44,Gloom,Grass,Poison,60,65,70,85,75,40,1,False
50,45,Vileplume,Grass,Poison,75,80,85,110,90,50,1,False
75,69,Bellsprout,Grass,Poison,50,75,35,70,30,40,1,False
76,70,Weepinbell,Grass,Poison,65,90,50,85,45,55,1,False
77,71,Victreebel,Grass,Poison,80,105,65,100,70,70,1,False
344,315,Roselia,Grass,Poison,50,60,45,100,80,65,3,False
451,406,Budew,Grass,Poison,40,30,35,50,70,55,4,False
452,407,Roserade,Grass,Poison,60,70,65,125,105,90,4,False
651,590,Foongus,Grass,Poison,69,55,45,55,55,15,5,False
652,591,Amoonguss,Grass,Poison,114,85,70,85,80,30,5,False

143

SyntaxError: invalid syntax (<ipython-input-27-95cd6c39ca84>, line 2)